version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.9-gatsby
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: mysecret123
        port: 4466
        databases:
          default:
            connector: postgres
            migrations: true
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            database: prisma
  postgres:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma